### ISSUE TITLE
Champs magiques

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#148]
Je n'ai pas l’impression que ça s'applique dans certains cas, ça devrait faire un malus sur l'observation et combat astrale/focus de quelqu'un d'un autre alignement de son indice.
Il manque aussi les traditions sur les adeptes qui sont aussi touchés sur leurs pouvoirs.
Ça applique des bonus de limite sur les sorts d'un mage de cette tradition aussi.

**Comment by tbzt** [comment]
Je suis en train de vérifier les règles de champs magiques.

L'interprétation peut être sibylline et pour les focus cela devra attendre le retoilettage. Pour les adeptes cela me semble complexe à automatiser.
