### ISSUE TITLE
Gestion de l'indice global des connaissances/langues

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#150]
Ajouter la possibilité d'augmenter l'indice de toutes les compétences de connaissance avec des choses de type : implant "Amélioration mnémonique", totem corbeau.
Si possible aussi les compétences de langues avec un trait de type linguiste qui ajoute +1 à toutes.

**Comment by tbzt** [comment]
Tu pourrais lister les items et les effets concernés (si possible avec les références de bouquin associées) pour se rendre compte ?

**Comment by xRazoulx** [comment]
Amélioration mnémonique p464 du libre sr5 de base :
L’amélioration mnémonique ajoute son indice à la réserve de dés pour les tests de compétences de connaissances, langues et tests liés à la mémoire ainsi qu’à la Limite mentale.
Raven : Book of the Lost, p. 121 :
Magician
+2 dice to Detection spells or summoning ALL spirits IF with Code of Honour (Harmony with Nature or Shaman's Code) and bargains with the spirit (choose one).
Adept
Enhanced Perception (2) for free.
All
2 to all Knowledge skills.
Disadvantage
WIL + CHA (3) to resist trying to acquire something valuable

**Comment by tbzt** [comment]
Merci, c'est faisable. À voir si ce n'est pas trop lourd pour ces seuls deux éléments. Je vais voir ce que ça donne.

**Comment by deurk** [comment]
Should be good with [575956c](https://github.com/shadowfoundry/sr5/commit/575956cf92f2fa97d8619954e6a041b6c85bde9b)
