### ISSUE TITLE
Compendium error for some programs

### ISSUE THREAD

**Issue by deurk** [shadowfoundry/sr5#167]
Cannot drag and drop `Goudron` and `Guerre Electronique` in `Programs`

**Comment by karmaroms** [comment]
yes, I've notice this : you can't click anything behind the contextual help :/

**Comment by deurk** [comment]
Fixed in [2957c71](https://github.com/shadowfoundry/sr5/commit/2957c717f3c4488dabcdfdae4243b8dfe97110de).
