### ISSUE TITLE
Tri sur l'initiative

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#199]
Bouton permettant de lancer un tri sur l'initiative ou la possibilité de déplacer le personnage sur l'ordre d'initiative. Très utilisé dans le cas d'un changement manuel d'initiative.

**Comment by karmaroms** [comment]
Le tri fonctionne si l'acteur n'a pas encore joué. 

Si l'initiative est modifiée lors de la phase d'action du joueur (parce qu'il fait une action qui réduit son initiative, par exemple), l'ordre dans le tour ne change pas avant la prochaine phase. Idem si le joueur fait une défense active qui lui diminue son initiative et qu'il a déjà joué. 

Sinon un personnage peut se retrouver à jouer 2 fois dans la meme phase d'initiative 
Par ex, Bob, init 16, joue à 16.
Grunt joue à 14, tire sur Bob qui fait une défense active amenant son init à 11.
Si on retri l'initiative, Bob aura a nouveau la possibilité de jouer à 11, ce qui est faux.
A la fin de la passe, on retranche 10, Bob jouera la prochaine passe à 1.


La dernière maj va fixer le bouton "Mettre à jour le combattant". La valeur d'initiative rentré ici provoque un tri sur la liste des combattants.
