### ISSUE TITLE
Actions matriciels VO et Retarder ses actions

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#204]
Les actions matriciels vo vont être incluse dans la version actuelle de foundry ?
Un des joueurs de ma table utilise des action matriciel assez sympa du bouquin Kill code :
"I AM THE FIREWALL" , qui permet de booster la défense du groupe contre une action complexe  et un -5 à son initiative actuel.
Ou encore l'action matriciel "INTERVENE".
Vu que ce sont des actions matriciels qui sont faites à tous va, il y a plein de -5 qui sont à réaliser, c'est assez récurant à faire et surtout c'est une action du PJ.

Si c'est pas possible, peut être donner le pouvoir aux joueurs de se réduire son initiative, ça pourrait être utiliser par la même occasion pour "retarder ses actions" (ldb p163) , ce qui est permit dans les règles de base.
Retarder l'init ça arrive régulièrement, par exemple pour se caler avec l'init de quelqu'un d'autre, un esprit par exemple qui attend un ordre, un drone, attendre un PJ etc.

**Comment by tbzt** [comment]
closes with #398
