### ISSUE TITLE
Pouvoir hémoragie

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#212]
Il manque le pouvoir d'esprit Hémorragie (grimoire des ombres p91) dans "catégorie" "pouvoir d'esprit" et "propriété" des "effets sur le système"

**Comment by tbzt** [comment]
Je ne comprends pas bien pourquoi il le faudrait dans les propriétés, vu que ce n'est pas visible, ce n'est pas plus utile dans les pouvoirs optionnels (ce qui l'indiquera ensuite sur la fiche de l'esprit) ?
