### ISSUE TITLE
Implement  a `Double Essence Loss from Augmentations` system effect

### ISSUE THREAD

**Issue by deurk** [shadowfoundry/sr5#217]
Needed by `Weak Immune System` negative quality

**Comment by karmaroms** [comment]
Actuellement on peut, meme si y'a probablement mieux :
![image](https://user-images.githubusercontent.com/77210927/162383398-14773996-efc0-49ca-a8af-484a35e510ea.png)

**Comment by deurk** [comment]
My bad, looked into `Special cases` on the item, not the system.
