### ISSUE TITLE
Issue with the defaulting skills

### ISSUE THREAD

**Issue by zechrub** [shadowfoundry/sr5#22]
Could you please hide or unable the defaulting skills dice pool?

**Comment by deurk** [comment]
Hi, do you mean like the second screenshot below?

![image](https://user-images.githubusercontent.com/498032/147590356-284ffc44-5539-4e53-a316-a489f907037c.png)
![image](https://user-images.githubusercontent.com/498032/147590368-0ba06679-e62f-40c2-a31e-c246582d9984.png)

**Comment by zechrub** [comment]
there are some skill which are not "defaultable". For this ones the DP should be hidden if it's not coming from a Skill groups or not with value null. Here for exemple Archery should not be hidden but Artisan yes
