### ISSUE TITLE
Bug focus de maintien

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#232]
Toujours une pénalité[maintien de sort] de -2 alors que le sort est sélectionné dans le focus de maintien

**Comment by karmaroms** [comment]
Vérifie que le focus est bien activé, et surtout que son indice est supérieur à la puissance du sort maintenu.
Chez moi ca fonctionne.

**Comment by xRazoulx** [comment]
Exact c'était la puissance du sort qui était supérieur au focus
