### ISSUE TITLE
Minor: Add tooltips on buttons to switch display on actor sheet

### ISSUE THREAD

**Issue by VincentVk9373** [shadowfoundry/sr5#25]
<img width="361" alt="2021-12-29_23h04_18" src="https://user-images.githubusercontent.com/4115073/147706899-66c911e8-081b-4cec-866c-8489129b5da9.png">

**Comment by karmaroms** [comment]
All infos are on the contextual help, bottom left.
![image](https://user-images.githubusercontent.com/77210927/147707058-5760b603-b263-43bd-b2e7-4bbeb885dfcd.png)

But why not :)

**Comment by VincentVk9373** [comment]
I was looking near the mouse, my bad :-)
As said in title, really minor
