### ISSUE TITLE
Issues with extended Roll

### ISSUE THREAD

**Issue by Qwetsh** [shadowfoundry/sr5#312]
Hi, 

There is an issu with extended roll, it doesnt work at all. 

error log : 

`roll-message.js:530 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
[Detected 1 package: system:sr5]
    at Function.updateRollCard (roll-message.js:530)`

i'll try to find the bug.

**Comment by karmaroms** [comment]
It works on dev branch, already fixed.
