### ISSUE TITLE
Chat message with SR6 purple contour with SR5 theme

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr5#319]
Using SR5 theme, there is a SR6 purple contour on message in the chat window.

![image](https://user-images.githubusercontent.com/17324443/191203334-84a0e5b6-e677-41b3-b6a4-d308aaa92ff5.png)

**Comment by karmaroms** [comment]
This color depends on the user color choice, it helps to identify who is the user owner of the message. You can change it.
![image](https://user-images.githubusercontent.com/77210927/191205558-d4930248-18e7-4f32-9ec5-afdfaa300069.png)
(and yes I need to skin this window)
