### ISSUE TITLE
Full defense bonus is not kept on the next defense

### ISSUE THREAD

**Issue by VincentVk9373** [shadowfoundry/sr5#32]

**Comment by karmaroms** [comment]
It should be possible when actor is in active combat (with combat tracker).

**Comment by gdelmee** [comment]
Maybe with a state like the cumulative recoil? Then doing something else than a defense will void this state.

**Comment by VincentVk9373** [comment]
My GMs consider the full defense bonus to be active even if the character does an action

**Comment by gdelmee** [comment]
Just checked the French core rule book pp. 191-192.
Bonus last until the end of the combat turn and prevent any other action.
