### ISSUE TITLE
Range display on Illusion spells is mixed up

### ISSUE THREAD

**Issue by QBallStan** [shadowfoundry/sr5#320]
On illusion spells:

- when "Line of Sight" is selected it shows up as "LOS(A)" on the character sheet.
- when "Line of Sight (Area)" is selected it shows up as "A" on the character sheet.
![Screenshot_24](https://user-images.githubusercontent.com/114283961/192088657-321ee332-3b15-47e9-acb8-8fca2b784069.png)

**Comment by karmaroms** [comment]
Simple translation key problem in english (it's ok in French).
Fixed in next release.
