### ISSUE TITLE
Bug arme focus

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#338]
Quand on édite une arme focus ca duplique automatiquement la ligne arme focus et on ne peut plus la supprimer, le seul moyen de réinitialiser la chose est de retirer l'arme lié du focus et de la remettre
![2022-10-22 23_55_48-Dawn of The Artefacts 3 - Minuit • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/99096756/197363802-e54f99e5-e208-441a-ab55-2a4aa72980e5.png)

**Comment by tbzt** [comment]
closes #344
