### ISSUE TITLE
Add perception types for effects

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr5#36]
Having both cyberears with audio amplification 3 and cybereyes with visual amplication 3, both add 3 to the mental limit for perception roll and 3 dices when in wifi. But the first one for earing perception only and the second one for visual perception only.

As of now, I can only set the effect on the perception in general:
![image](https://user-images.githubusercontent.com/17324443/147779429-0d6c6a91-080f-4c10-9a71-c01fd041f608.png)

Then, my perception roll has both of them:
![image](https://user-images.githubusercontent.com/17324443/147779332-2a1b4e5f-1319-4326-95ad-6f0389aa4fec.png)

Rolling a skill test, I don't have a way to select the type of perception all bonuses apply:
![image](https://user-images.githubusercontent.com/17324443/147779520-8c78bed3-4fce-407a-92e3-4accb7c1f3f0.png)

As of now, I have to accomodate the test to avoid such result:
![image](https://user-images.githubusercontent.com/17324443/147779341-c5cee3ae-60c3-40b1-b730-b5e5e66635ce.png)

**Comment by karmaroms** [comment]
Yes, currently, different "type" of Perception are not supported.
But it's planned.
