### ISSUE TITLE
Serrures, maglock et appareil

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#393]
Ajout si possible d'un champ texte éditable sur les Appareils et Maglocks pour le cas par exemple des maglock biométriques, pour ajouter des aides concernant les jets de dés sur ces dispositifs. Toutes les variantes de jet de dés ne sont pas automatisés, ca serait très pratique.
Sur les appareils ça permettrais de mettre par exemple des informations sur les caméra, par exemple senseur thermographique, la couverture des caméras, etc.
Également des notes sur les différents dispositif de sécurité caché (dalle à pression, détecteur de mouvement, etc.)
Le champ texte serait déjà formidable sans automatiser les différents systèmes.
Aussi, si possible ajouter les options serrure et clé à transpondeur dans maglock (qui serait peut être à renommer autrement) et seraient utilisés avec le système de serrurerie. Dans le cas la clé avec transpondeur, l'aide dans le champ texte permettrais par exemple de mettre le test non automatisé (Matériel électronique + Logique [Mentale] (indice de la serrure, 1 minute) )

**Comment by tbzt** [comment]
Tu peux m'indiquer où se situent les règles pour "clé avec transpondeur" ?

**Comment by xRazoulx** [comment]
Dans le livre de base p365 vers les serrures et maglock.
Il faut faire le test de serrurerie standard et un autre de matériel électronique avec un malus si la même personne fait les deux : 
Les clés à transpondeur contiennent une résistance calibrée qui complète un circuit dans la serrure. Pour crocheter un tel verrou à la main, un kit électronique est nécessaire afin de générer les caractéristiques électriques appropriées. Cela requiert un test étendu de Matériel électronique + Logique [Mentale] (indice de la serrure, 1 minute) en même temps que l’on crochète la serrure. Si c’est le même personnage qui crochète la serrure et calibre le flux électronique, il subit un modificateur de -2 dés de réserve aux deux tests.
