### ISSUE TITLE
Bug esprit veilleur

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#394]
Le déploiement d'esprit veilleur depuis un acteur fonctionne, mais quand on veut le ranger ca met cette erreur :
![image](https://user-images.githubusercontent.com/99096756/220636194-bba50eea-8747-4d46-add5-31a3dde00598.png)

**Comment by karmaroms** [comment]
Fixé dans la prochaine maj.

**Comment by tbzt** [comment]
+ homoncule
