### ISSUE TITLE
Problème pour rentrer un véhicule sur fiche grunt

### ISSUE THREAD

**Issue by DjamZee** [shadowfoundry/sr5#440]
https://cdn.discordapp.com/attachments/925859566858686494/1162846098256318595/image.png?ex=653d6bd2&is=652af6d2&hm=5e492cefdff7bb426a8113dd487057ca6d99a0069ca1119b758cb5838cadde62&

Problème pour rentrer un véhicule dans une fiche de contact (gruntsheet). Hier ca fonctionnait, la j'y ai juste ajouté sa monture d'arme, un canon d'assaut, et ses autosofts

**Comment by tbzt** [comment]
The problem was the removal of the intermediate actor between the two deployed actors.
