### ISSUE TITLE
Ajout de la fonction "Peut faire un test"

### ISSUE THREAD

**Issue by DjamZee** [shadowfoundry/sr5#442]
Hello,
Il serait intéressant d'ajouter la fonction "Peut faire un test" à la fiche de cyberware car certain, comme le Système de contrôle traumatique (bon c'est pas vraiment du cyber mais ca utilise la fiche) sont en mesure de faire des test.

**Comment by tbzt** [comment]
ça me semble être l'artillerie pour un cas très particulier, tu as d'autres cas ?

**Comment by DjamZee** [comment]
arf oui, j'en ai vu plusieurs au fil du temps mais j'ai pas noté lesquels :/
