### ISSUE TITLE
Ajout des attaques ciblées de Run & Gun

### ISSUE THREAD

**Issue by DjamZee** [shadowfoundry/sr5#444]
Serait-il possible d'ajouter les attaques ciblées de Run & Gun au menu déroulant déjà existant ainsi que les modificateurs adéquats ?
Avec une case à cochée pour les traits et art martiaux qui en réduisent le cout, pour faire les choses bien ^^

**Comment by tbzt** [comment]
I don't understand the request, it's already the case. You need to activate Run&Gun in the system options.
