### ISSUE TITLE
Bug de calcul monture d'arme

### ISSUE THREAD

**Issue by Hemoglobyne** [shadowfoundry/sr5#449]
La monture d'arme standard, dissimulé, fixe, à distance apparait avec un score de slots de 10 au lieu de 6

**Comment by deurk** [comment]
![image](https://github.com/shadowfoundry/sr5/assets/498032/c2d62e70-0918-4248-88ba-b688c6c54707)

Je ne vois pas la même chose, une monture créée manuellement montre bien 6 slots dispo. Erreur de paramétrage ?
