### ISSUE TITLE
Capacité d'armure

### ISSUE THREAD

**Issue by xRazoulx** [shadowfoundry/sr5#452]
Il y a un bug je pense sur le calcul des capacités dans les armures, pour ignifuge par exemple ça me met [8] en capacité alors que c'est indice x1
<img width="718" alt="2023-12-11 13_02_22-• Discord _ #aide _ ShadowFoundry" src="https://github.com/shadowfoundry/sr5/assets/99096756/55d64ec2-9e86-4c79-a608-66450fb610bb">

**Comment by tbzt** [comment]
Je n'arrive pas à reproduire le bug, cela fonctionne bien de mon côté avec les capacités des armures et celles de leurs accessoires.
