### ISSUE TITLE
Modif de l'éditeur de page dans les journaux

### ISSUE THREAD

**Issue by DjamZee** [shadowfoundry/sr5#466]
![Capture d'écran 2024-02-16 190159](https://github.com/shadowfoundry/sr5/assets/118370712/ea98bb39-6f8c-4d27-8ba2-761f9668a29b)
Bonjour, serait-il possible de réduire la taille du footer ou de la zone de texte pour éviter le chevauchement car dans ce cas le texte est en arrière plan et c'est pas tres pratique ^^

**Comment by tbzt** [comment]
Il y a la possibilité de scroller et de modifier la taille de la page. J'ai légèrement réduit.
