### ISSUE TITLE
Bug utilisation armes a feu

### ISSUE THREAD

**Issue by QBallStan** [shadowfoundry/sr5#473]
Quand un compte joueur utilise une arme, les munitions ne sont pas décomptées et le type d'arme est reset (voir screenshot)
![Screenshot_27](https://github.com/shadowfoundry/sr5/assets/114283961/9a62085b-8763-4623-94eb-1a5f6cef9e9f)

Aucun soucis lorsque l'arme est utiliser par un compte GM.

Meme problème sur un serveur neuf, nouvelle installation et 0 modules actif.

Version Foundry 11.315, Sr5 11.0.14

**Comment by tbzt** [comment]
Est-ce que vous pouvez transmettre ce qu'il y a dans la console de debug (F12 sur Foundry) quand vous utilisez une arme ? A priori ça fonctionne de mon côté.

**Comment by QBallStan** [comment]
Je n'ai aucun message sur la console.

J'ai fait le test sur une nouvelle session avec 0 modules actif.
J'ai aussi fait le test sur une installation fraiche sur "The Forge". Meme problème.

J'insiste sur le fait que le bug n'apparait que lorsque l'arme est utilisée par un **compte joueur**. Je n'ai aucun problème quand l'arme est utilisée par un compte GM ou assistant GM.
