### ISSUE TITLE
Difficultés sur l'édition de la Crédibilité

### ISSUE THREAD

**Issue by Cebrindil** [shadowfoundry/sr5#476]
Outre mon avis personnel sur la difficulté d'éditer le score manuellement (l'édition par clic gauche/clic droit est d'une ergonomie très discutable), le souci que je signale vient en fait de l'impossibilité de descendre sous la base 0 pour ce score. Il est donc impossible de "dépenser" de la crédibilité pour réduire sa rumeur, ou bien de modifier à loisir le score si on désire utiliser un système de réputation différent.

**Comment by tbzt** [comment]
doublon #207
