### ISSUE TITLE
Specialisation does not add bonus on automatics

### ISSUE THREAD

**Issue by VincentVk9373** [shadowfoundry/sr5#48]
Rolling from the skill
<img width="398" alt="2022-01-08_17h19_01" src="https://user-images.githubusercontent.com/4115073/148651587-7a20cb26-9152-4e3e-a297-708c42035013.png">

Rolling from a weapon, not possible to select at all
<img width="312" alt="2022-01-08_17h21_01" src="https://user-images.githubusercontent.com/4115073/148651661-82708dcd-097d-45fb-bd21-de12b96056d2.png">

Specialisation Street on etiquette works.
<img width="397" alt="2022-01-08_17h19_37" src="https://user-images.githubusercontent.com/4115073/148651611-e6805fd1-2c18-4ff1-b18c-3e7663186516.png">

Workaround: add to the various modifiers.

Same for other combat active skills

**Comment by karmaroms** [comment]
Rolling Combat skill from skill tab is not really the way to roll attack. Use weapon roll on Combat tab.
You can activate Specialization permanently for a weapon with the toggle at the beginning of the line.
![image](https://user-images.githubusercontent.com/77210927/148651865-e069bd71-4a2b-4a09-b177-b41c3b22f492.png)
