### ISSUE TITLE
Edition des pouvoirs et des focus

### ISSUE THREAD

**Issue by Hemoglobyne** [shadowfoundry/sr5#492]
Impossible d'éditer les pouvoirs

**Comment by QBallStan** [comment]
J'ai effectivement le message suivant lorsque j'essaye d'acceder a un pouvoir a partir du compendium:
![Screenshot_27](https://github.com/user-attachments/assets/1ffa333d-1626-43d3-8167-836cc47f1c1f)

Et le message suivant lorsque j'essaye de creer un nouvel item "pouvoir":
![Screenshot_28](https://github.com/user-attachments/assets/99895e75-b120-491f-8e60-3eb511607623)

**Comment by Hemoglobyne** [comment]
PS : sa marchais avec la 12.0.1
