### ISSUE TITLE
Tooltips translation fr

### ISSUE THREAD

**Issue by Gabryel666** [shadowfoundry/sr5#81]
One super minor detail :
when selecting a token, the tooltips on the icons : "Assign status effect" and "Toggle combat state" do not have a french translation.

**Comment by deurk** [comment]
Must have been fixed by core translation since the issue creation :)
![image](https://user-images.githubusercontent.com/498032/155120936-c616ec6f-8107-4f5d-9f87-e4ece39f0a54.png)
