### ISSUE TITLE
Add overflow monitor

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr5#84]
When the physical monitor is overflowing, additional separated red boxes are shown. But the rest of the time, we can't see it.

Adding the overflow monitor will allow the player to see and manage how many rounds he has left to be stabilized before the character dies.

**Comment by deurk** [comment]
How is the current system preventing that? What is the proposition: to display it all the time?

**Comment by deurk** [comment]
Now always displayed, disabled when physical monitor is not full.
![image](https://user-images.githubusercontent.com/498032/162612010-174e43a5-892c-452b-8338-6d3345cdc490.png)
